/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _ios_kernel_h_
#define _ios_kernel_h_
//---------------------------------------------------------------------------------
extern const unsigned char ios_kernel[];
extern const int ios_kernel_size;
//---------------------------------------------------------------------------------
#endif //_ios_kernel_h_
//---------------------------------------------------------------------------------
